import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import type { MediaProvider, StoredMedia } from "@/lib/media/provider";

/* THE STORE FOR A LAPTOP, AND FOR NOTHING ELSE.
 *
 * It writes under `.data/media` — beside `.data/pglite`, which is where this
 * project already keeps the things that are real but local — and the files are
 * read back through /api/media/…. That makes the whole poster feature testable
 * and demonstrable with no account anywhere, which is the point.
 *
 * ═══ IT REFUSES TO RUN IN PRODUCTION, AND THAT IS THE FEATURE ═════════════
 *
 * A serverless function's disk is not shared between the instances serving the
 * same site and does not survive the instance being recycled. A poster written
 * there appears for some visitors, for a while, and then does not — which is
 * strictly worse than no poster, because it looks like it worked and fails
 * silently a week later when somebody is looking at the wrong screen.
 *
 * The guard is in `mediaReadiness()` so the admin screen can say so BEFORE
 * anybody picks a file, and it is repeated here because a module that can
 * destroy data must not depend on its caller having remembered to check. */

const ROOT = path.join(process.cwd(), ".data", "media");

function assertNotProduction(): void {
  if (process.env.NODE_ENV === "production") {
    throw new Error(
      "MEDIA_STORE=local ne sme da radi u produkciji — datoteke na serveru nestaju. " +
        "Podesite MEDIA_STORE=vercel-blob ili MEDIA_STORE=s3.",
    );
  }
}

/* A key is generated by lib/media/images.ts and is already known to be safe.
   This checks it AGAIN, because the one bug that matters in a file writer is
   the one where a key climbs out of its directory, and "the caller validated
   it" is how that bug ships. */
function resolveWithin(key: string): string {
  const full = path.resolve(ROOT, key);
  const root = path.resolve(ROOT);
  if (full !== root && !full.startsWith(root + path.sep)) {
    throw new Error("Neispravan ključ datoteke.");
  }
  return full;
}

export const localMediaProvider: MediaProvider = {
  id: "local",

  async put({ key, body }): Promise<StoredMedia> {
    assertNotProduction();
    const full = resolveWithin(key);
    await mkdir(path.dirname(full), { recursive: true });
    await writeFile(full, body);
    return { key, url: `/api/media/${key}` };
  },

  async remove(key: string): Promise<void> {
    assertNotProduction();
    /* A row that carries a URL rather than a key still resolves, because the
       development URL is the key with a prefix. */
    const cleaned = key.startsWith("/api/media/") ? key.slice("/api/media/".length) : key;
    if (cleaned.startsWith("http")) return;
    await rm(resolveWithin(cleaned), { force: true });
  },
};

/* Where /api/media/[...key] reads from. Exported so the route does not have to
   know this module's idea of a directory. */
export function localMediaPath(key: string): string {
  return resolveWithin(key);
}
